Native Binary for Windows Generator
Bram-Hub/Legup pull request #137
Opened 2022-06-13 06:34 UTC by TrevorBrunette

You can now generate a Windows installer for Legup! Please don't upload the generated installer in the git repo since it contains the jar and entire Java Runtime Environment. It can be generated by running the Inno Setup script at `native/windows/legup_setup.iss`. (You must have Inno Setup installed).

- Using launch4j I created the executable to launch the jar file.
- Using Inno Setup I created an installer which installed the jar file, .exe launcher, and JRE into a legup directory.
- Created Logger class to manage logging. 
- Modified logging to log into `(user.home)/.legup/`. (See #135 for reasoning)
- Modified newer Java methods s.t. compilation using Java 1.8 was possible (since we are currently targeting 1.8).

2022-06-20 04:12 UTC, TrevorBrunette commented
I changed build.gradle - be sure to see the diffs there to make sure that is all good. I also added a task to build the native Windows executable. This gradle task only runs on Windows since it uses Inno Setup. Try running the 'buildNativeWindows' task to generate an executable, and use that for a release alongside the JAR file!

2022-07-21 20:27 UTC, charlestian23 requested changes
When attempting to run the `buildNativeWindows` command, I get an error:
```
Execution failed for task ':buildNativeWindows'.
> Process 'command 'cmd'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```
I ran this through IntelliJ, though Chase also tried running it through the command line and also got the same error on his machine.

We were able to get an executable file by running `createExe`, though we're not sure if that's what you intended us to use.

The executable file generated also has some problems. Below is the home screen that we get after compiling and running the jar file:
![image](https://user-images.githubusercontent.com/46334090/180308764-6293f4ab-fd38-4746-ad6a-0f2fe46717cb.png)
And this is the home screen after compiling and running the executable file (with `createExe`):
![image](https://user-images.githubusercontent.com/46334090/180308933-b9bcea70-462e-4832-8872-00fe456274c6.png)
Not sure why this happens. Can you look into these few issues? Other than that, good work!

2022-08-13 20:34 UTC, TrevorBrunette commented
I have resolved all of the merge conflicts. See the buildNativeWindows and createExe task declarations in build.gradle for comments on usage. The gist is that you will run buildNativeWindows to create the final .exe installer file for a release. 

The reason this task would fail would be because the InnoSetup script needs to be pointed to the path of whatever release of Java is to be bundled with the release. I set it up on my computer, so I gave it the path to the latest installation of Java on my computer. It would be unwise to include an entire JRE in the repository to ship. Maybe it is possible to have a task which downloads the latest version of whichever JRE we need and places it in some known temporary location. Including that within buildNativeWindows would likely fix the issue. Again, see the comments in build.gradle and the InnoSetup script for more information. Automatically gathering the latest JRE needed should be it's own issue and PR.

2022-08-17 02:55 UTC, charlestian23 approved these changes

2022-08-17 02:55 UTC, merged