Implemented general empty puzzle functionality and started with sudoku
Bram-Hub/Legup pull request #179
Opened 2022-07-02 05:22 UTC by mattsweet417

2022-07-04 00:22 UTC, charlestian23 requested changes
Doesn't seem to work for me, can you make sure you committed everything to your fork? I remember you had it working.

2022-07-05 05:29 UTC, mattsweet417 commented
Should be all set now, I uncommented and moved a set window title line. It was null in puzzle editor where it was originally for proof editor because puzzle editor has to create the puzzle instead of load it up and then set the title.

2022-07-05 14:42 UTC, charlestian23 approved these changes

2022-07-05 14:42 UTC, charlestian23 commented
Seems to work now, nice!

2022-07-05 14:42 UTC, merged