Changedd the yes/no/cancel options to just yes/no
Bram-Hub/LEGUP pull request #453
Opened 2023-02-14 21:47 UTC by VortiganOfficial

self explanatory

## Description

Closes #[424](https://github.com/Bram-Hub/LEGUP/issues/424)

## Type of change

- Enhancement (improvement to an already existing feature)

## How Has This Been Tested?

## Checklist:

- I have performed a self-review of my code
- My changes generate no new warnings
- The jar compiles and runs perfectly

2023-02-17 21:29 UTC, charlestian23 requested changes
The changes are good. However, the fact that the buttons aren't centered slightly bothers me. See the image below:
![image](https://user-images.githubusercontent.com/46334090/219797315-91db71ea-b67d-4077-b232-534d6fa8b811.png)

Can you change it so that the two buttons are centered?

2023-02-17 21:41 UTC, VortiganOfficial commented
Will do!

2023-02-24 21:15 UTC, charlestian23 commented
Alright, it seems like you were right. FlatLaf formats the JOptionPane dialog like that, and it'll be a pain to change. So we'll just live with it. It's fine if it's not centered.

2023-02-24 21:16 UTC, charlestian23 approved these changes

2023-02-24 21:16 UTC, merged