Fixed the nullpointer exception when cencelling batch grader
Bram-Hub/LEGUP pull request #481
Opened 2023-02-28 21:13 UTC by VortiganOfficial

## Description

I couldn't find any particular place where the code was breaking other than the particular line that crashed, I tried putting return if null statements at certain points but nothing seemed o fix it alone, so I just started putting them anywhere that made sense

Closes #438 

## Type of change

- Enhancement (improvement to an already existing feature)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?

## Checklist:

- I have performed a self-review of my code
- My changes generate no new warnings
- The app opens on my laptop

2023-02-28 21:41 UTC, Corppet requested changes
This code is not formatted correctly to our `checkstyle` standards. Additionally, randomly putting `null`-checks-and-returns within the code is not a good approach to solving this issue (consider `try-catch` instead).

2023-02-28 22:14 UTC, VortiganOfficial commented
Sorry, there was a miscommunication, the placements were not random. I put them after the lines that opened the preferred directory, the folder containing the solutions, getting the selected file, and creating the result file. The reasoning for each placement is as follows:

I feel that there should be a return if null after opening the preferred directory  because there is a default preferred directory and it being null is an error

I put a return if null after opening the folder because that solves the main problem, clicking cancel on the folder browser after clicking the batch grader button

I put a return if null after opening the selected file because no operations can be done on a file that is null, leading to possible bugs in the future

I put a return if null after creating the result file because the file might not get created if the program doesn't have write permissions in a certain folder, which is an error. I understand that this probably should be followed with an error message to the user, and I will open an issue for this as I don't know the specifics of how exactly to do that.

Lastly, I don't understand how I would implement try-catch blocks for this problem given my very limited experience with the language. If you have any more details or pointers to tutorials I will gladly follow them, but all tutorials I have found so far catch any and all exceptions, which is probably bad practice because the errors can be anything

I will fix the checkstyle errors, thank you for pointing those out to me. It compiled fine for me on my laptop, so I assumed it would be fine to create a pull request

2023-03-03 21:12 UTC, Corppet commented
I'll approve these changes since after looking at them again they're good enough to get the issue done.

For catching specific exceptions, simply specify the exception you want to catch in your `catch` block.
```
try
{
    // do something
}
catch (SpecificException see)
{
   // do something with se
}
catch (Exception e)
{
   // do something with e
}
```

2023-03-03 21:12 UTC, Corppet approved these changes

2023-03-03 21:12 UTC, merged