Fix for LightUp and TreeTent Puzzle Creators
Bram-Hub/LEGUP pull request #530
Opened 2023-04-08 01:54 UTC by rspacerr

## Description

This should fix both the LightUp and TreeTent puzzle creators, with functionality to place objects in the creator, save the puzzle and load it in the puzzle editor. 

Closes #372 and #503

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Enhancement (improvement to an already existing feature)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?

I opened LightUp and TreeTent independently in the puzzle creator, placed objects, and saved the file, which loaded in the puzzle editor. Fair warning, I was unable to test in the new gradle version since for some reason my build errors out which I am trying to fix. Warning 2, I found that closing the file using ctrl-q from the puzzle editor and loading into the puzzle creator causes a bug, which I think is a native error since this happens for Nurikabe too. I can make an issue after I fix my gradle.

## Checklist:

- [X] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (if applicable)
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2023-04-14 20:32 UTC, Corppet requested changes
Please look at the files you are changing in this pull request. There are a lot of redundant changes that need to be addressed before I can approve/review anything here.

2023-04-21 20:45 UTC, Corppet requested changes
Changes are looking a lot better than before, though your changes are causing some tests in `TreeTent` to fail. Look in the `checkstyle` check for more details.

2023-04-22 18:26 UTC, charlestian23 commented
I seem to have fixed those issues Ivan mentioned in a separate pull request (#542). Seems like updating from `dev` didn't bring those changes over?

2023-04-25 14:03 UTC, charlestian23 commented on src/main/java/edu/rpi/legup/puzzle/lightup/elements/UnknownTile.java
We should not have Nurikabe IDs and images be used for Light Up puzzles. You should make a brand new ID and image for the Light Up unknown tile.

2023-09-29 20:49 UTC, Corppet commented
This PR is still a work in progress as not all the checks are successful. If you would like to contribute to this PR you can checkout the branch and try building the project locally to see the errors.

2023-12-01 20:41 UTC, jac-oblong commented
PR replaced by #629 and #692

2023-12-01 20:41 UTC, closed without merging