UI colors
Bram-Hub/LEGUP pull request #765
Opened 2024-03-19 20:31 UTC by FisherLuba

## Description

This will create a new file color-theme.txt that allows users to specify their own color scheme, and also allows LEGUP to provide a color blind scheme. It is currently a work in progress.

Closes 426

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Enhancement (improvement to an already existing feature)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?

## Checklist:

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2024-03-26 22:28 UTC, charlestian23 requested changes
Couple things:
- I would prefer if the checkboxes for dark mode and the colorblind mode still worked. Potentially this means that if those options are checked off, the settings should automatically go searching for this file. (This really should only apply to color-blind mode stuff, as you'll see in a later comment I have.) See the image below:
![image](https://github.com/Bram-Hub/LEGUP/assets/46334090/41b62f00-e362-4a4f-ab88-a86c0861786a)
- It seems like restarting LEGUP isn't saving any changes I make to the color scheme. For example, setting dark mode and then closing LEGUP and reopening it makes it light mode.
- Dark mode does not seem to function the same way as it did when we used Flatlaf dark mode. Perhaps you could just use the built in Flatlaf dark and light mode by default and only use a color theme file if the user specifies one. See the image below for dark mode:
![image](https://github.com/Bram-Hub/LEGUP/assets/46334090/128e0456-6561-4f4a-8a26-4018ff4a8c05)

2024-03-29 21:37 UTC, FisherLuba commented
I did some work on the LegupPreferences class because I noticed it was kind of annoying to work with. Before you had to do something like `LegupPreferences.getUserPref(LegupPreferences.<SOMETHING>).equals(Boolean.asString("false));`
Now, you can either do `LegupPreferences.<preference>()`, or `LegupPreferences.LegupPreference.<SOMETHING>.asBoolean()`.
I also made preferences use an enum instead of strings for the keys, which makes other methods more convenient.

I also noticed in some places that instead of getting the preference value, the string of the preference was being used instead for example WORK_DIRECTORY instead of `getUserPref(WORK_DIRECTORY)`. This commit should prevent that from happening in the future because the preference keys are now enums, so that code won't compile.

2024-04-02 21:40 UTC, FisherLuba commented
I added a checkbox for using a custom theme, now I just have to figure out how to make the button sizes and shapes the same as FlatLaf.

2024-04-12 20:19 UTC, charlestian23 requested changes
I still am getting issues with dark mode. I have dark mode toggled to be on when I open LEGUP and it's opening it in light mode. Additionally, when I try to toggle back to dark mode, it shows up like below:
![image](https://github.com/Bram-Hub/LEGUP/assets/46334090/2e05f489-153c-49df-8d09-30037918a49b)

However, dark mode does work now in the preferences menu after I re-toggle it to be on:
![image](https://github.com/Bram-Hub/LEGUP/assets/46334090/d183aec0-84ec-47b2-9e83-ceeb543dea1f)

Also, after working with this, I think it would be best to put dark mode, the color-blindness options, and the custom color file under its own section in preferences. Perhaps it would also be best to only show the custom color file if you select a checkbox in order to not confuse users. That way, if someone wants to put a custom color file, they have to check off "Custom Color File", which will untoggle any color-blind mode that is on and then read in colors from the file.

2024-04-12 20:55 UTC, FisherLuba commented
> I still am getting issues with dark mode. I have dark mode toggled to be on when I open LEGUP and it's opening it in light mode. Additionally, when I try to toggle back to dark mode, it shows up like below: ![image](https://private-user-images.githubusercontent.com/46334090/322126922-2e05f489-153c-49df-8d09-30037918a49b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5NTQ2MDcsIm5iZiI6MTcxMjk1NDMwNywicGF0aCI6Ii80NjMzNDA5MC8zMjIxMjY5MjItMmUwNWY0ODktMTUzYy00OWRmLThkMDktMzAwMzc5MThhNDliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDIwMzgyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjZWI5M2YwOGY0NTBhYjJmYTcxYjg4NjM5Y2EwN2IxOGNlYjgwMDYyMDQwZTZhYzk4MjBhMzZlODMzMzI5N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8RBYznhMpGwXviD_AgFiSSsNh4ON_UnMFYpkgfveF_A)
> 
> However, dark mode does work now in the preferences menu after I re-toggle it to be on: ![image](https://private-user-images.githubusercontent.com/46334090/322127793-d183aec0-84ec-47b2-9e83-ceeb543dea1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5NTQ2MDcsIm5iZiI6MTcxMjk1NDMwNywicGF0aCI6Ii80NjMzNDA5MC8zMjIxMjc3OTMtZDE4M2FlYzAtODRlYy00N2IyLTllODMtY2VlYjU0M2RlYTFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDIwMzgyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxYzk4MDQ1MGFhNzQ1OWJhMTY5MGFkZGIzMjA5MTM3YWU3YTUyZmU3Mzk2N2ZkYjdjN2ZhNGQyZDlhOWY3OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.elYUUBuEimsNIxbHkWEyHEJAs2OR9DPHfGVpDxcLRTU)
> 
> Also, after working with this, I think it would be best to put dark mode, the color-blindness options, and the custom color file under its own section in preferences. Perhaps it would also be best to only show the custom color file if you select a checkbox in order to not confuse users. That way, if someone wants to put a custom color file, they have to check off "Custom Color File", which will untoggle any color-blind mode that is on and then read in colors from the file.

Is the image with the latest commit? It doesn't show the checkbox for the custom color. 
I agree with hiding the color theme file option when the checkbox isn't checked, so I will implement that.

2024-04-16 18:19 UTC, charlestian23 commented
> > I still am getting issues with dark mode. I have dark mode toggled to be on when I open LEGUP and it's opening it in light mode. Additionally, when I try to toggle back to dark mode, it shows up like below: ![image](https://private-user-images.githubusercontent.com/46334090/322126922-2e05f489-153c-49df-8d09-30037918a49b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5NTQ2MDcsIm5iZiI6MTcxMjk1NDMwNywicGF0aCI6Ii80NjMzNDA5MC8zMjIxMjY5MjItMmUwNWY0ODktMTUzYy00OWRmLThkMDktMzAwMzc5MThhNDliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDIwMzgyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjZWI5M2YwOGY0NTBhYjJmYTcxYjg4NjM5Y2EwN2IxOGNlYjgwMDYyMDQwZTZhYzk4MjBhMzZlODMzMzI5N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8RBYznhMpGwXviD_AgFiSSsNh4ON_UnMFYpkgfveF_A)
> > However, dark mode does work now in the preferences menu after I re-toggle it to be on: ![image](https://private-user-images.githubusercontent.com/46334090/322127793-d183aec0-84ec-47b2-9e83-ceeb543dea1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5NTQ2MDcsIm5iZiI6MTcxMjk1NDMwNywicGF0aCI6Ii80NjMzNDA5MC8zMjIxMjc3OTMtZDE4M2FlYzAtODRlYy00N2IyLTllODMtY2VlYjU0M2RlYTFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDIwMzgyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxYzk4MDQ1MGFhNzQ1OWJhMTY5MGFkZGIzMjA5MTM3YWU3YTUyZmU3Mzk2N2ZkYjdjN2ZhNGQyZDlhOWY3OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.elYUUBuEimsNIxbHkWEyHEJAs2OR9DPHfGVpDxcLRTU)
> > Also, after working with this, I think it would be best to put dark mode, the color-blindness options, and the custom color file under its own section in preferences. Perhaps it would also be best to only show the custom color file if you select a checkbox in order to not confuse users. That way, if someone wants to put a custom color file, they have to check off "Custom Color File", which will untoggle any color-blind mode that is on and then read in colors from the file.
> 
> Is the image with the latest commit? It doesn't show the checkbox for the custom color. I agree with hiding the color theme file option when the checkbox isn't checked, so I will implement that.

I see now I didn't have the latest commits pulled. I think I found another problem. It seems that having dark mode checked off versus not having it checked off messes with the custom color theme. See the images below:
![image](https://github.com/Bram-Hub/LEGUP/assets/46334090/c5beb606-a99c-44a6-ace5-d4077b891219)
![image](https://github.com/Bram-Hub/LEGUP/assets/46334090/dd936f62-7e6f-4c64-8993-ed2494372049)
Notice how when dark mode is checked off that the background of some of the boxes is dark. I assume that this isn't the intentional behavior? Perhaps when a custom file is given, we should uncheck dark mode?

2024-04-16 19:32 UTC, FisherLuba commented
I can do that, it might be okay to leave that though so that a color theme file can just override the colors it wants to, so if the user still wants dark mode for everything else they can keep it. Right now the custom color theme file is just light mode colors.

2024-05-05 17:24 UTC, charlestian23 approved these changes
Just tested it, most of this seems fine. The deuteranomaly option doesn't work in preferences (tested in Short Truth Table and checking it off doesn't seem to change the elements from green to blue like they used to). However, I think we can just merge this and open an issue for someone to bug fix that in the future. @Chase-Grajeda you can decide how you want to handle that.

2024-06-01 08:16 UTC, Chase-Grajeda commented
There seems to be a bug with saving within the Puzzle Creator, which appears to be caused by the merge conflicts on `ProofEditorPanel.java` and `PuzzleEditorPanel.java`. When attempting to save a newly created puzzle, the process will fail silently and fail to save. Unable to merge until fixed

2024-06-01 15:26 UTC, FisherLuba commented
> There seems to be a bug with saving within the Puzzle Creator, which appears to be caused by the merge conflicts on `ProofEditorPanel.java` and `PuzzleEditorPanel.java`. When attempting to save a newly created puzzle, the process will fail silently and fail to save. Unable to merge until fixed

This should be fixed now.

2026-04-23 22:31 UTC, merged

2026-04-24 02:43 UTC, FisherLuba commented
I was just looking back at this merge request, and it looks like I made a mistake and https://github.com/Bram-Hub/LEGUP/pull/765/changes#diff-c3366bcfc9720e5ebd403b23719d89b11679605d9e417a8b1696e92ec2f21a5aR101 should be replaced with https://github.com/Bram-Hub/LEGUP/pull/765/changes#diff-c3366bcfc9720e5ebd403b23719d89b11679605d9e417a8b1696e92ec2f21a5aR88.